language: node_js
sudo: false
node_js:
- '6'
- '7'
- stable

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start

script: mocha

notifications:
  slack:
    rooms:
      secure: nDVt+vH/5vTXU7IIoC4yrUnW5os4ZHlqpO/si3KZ9HMQc1YdYOyBlLnjJSxLEVCefkJeK2Ku316QgLF6jYMC8UUTf9ktsHUt6hrqw0nzmlsHoi+TtfXKiMY0iVqKbguhA3L74f+pJN5C59Kg8H+ZPgSpKHKLyprY076G90hEN2jv5KmxwH5LMm4IMrn27ka8klGLXJ3XbUHr5q4zhKg5KZRWcvevPR9mdmT/7HWoD6T2lb0SwaJMqlGCurZwUGycEScE27eOhl+Yl83tcRRPmb0mjWdnLbKVPZHb2/JWpegQLg24jQyPTl1GjP1HHGyko7VkRS1C0+IoFFLRp1uKw+WJy2fYfi7sPNodIi7UCAXnGfVq6nUmlMoC5nE5Yrl5ovxGt56fGI/2PDoJ6hppkfDU7rlgM4UGs3I+hmz1LGhJ2ataiTNj1T88kHVA968UB953D6UvK8V9HfjaGw7WeXaTTxkuiyKoRX7uMeenF4T6IRh2Iw5KnFEtJ1nzZ+oE+OavAKzd3TKDJntrw850lQTvrP7QUyZteXLVK8ofYOeEmF9ihQLDPU0QzpyLEktVYilQA/Gxr0Z6kTtvC7WIdDLn7lbfZzGcZb2jnOh+ZndxWuMiwqrLwxxHm0pirglZC42oRBbHmcBVv3gz4O6+hg3VINzzThtBOWscIWGH/ls=
